version: '3.8'

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: damncrud
    volumes:
      - .:/var/www/html
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html"]

  db:
    image: mysql:5.7
    container_name: my_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: damncrud
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

