name: CI/CD Pipeline with Selenium and DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          until docker exec my_db mysqladmin ping --host=db --silent; do
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Import Database
        run: |
          docker exec -i my_db mysql -u root -proot damncrud < db/damncrud.sql

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pytest pytest-xdist selenium webdriver-manager pymysql

      - name: Run Pytest Tests in Parallel
        run: |
          sleep 10
          curl -v http://localhost:8000 || echo "Web service belum siap"
          docker exec my_app pytest -n auto test_damncrud.py -v

  dast_scan:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "http://localhost:8000"
          fail_action: true
