name: CI/CD Pipeline with Selenium and DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          until docker exec my_db mysqladmin ping --host=db --silent; do
            sleep 1
          done

      - name: Install Python dependencies
        run: pip install pytest pytest-xdist selenium

      - name: Install webdriver_manager
        run: pip install webdriver_manager

      - name: Run tests in parallel
        run: pytest -n auto test_damncrud.py

  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run ZAP Baseline Scan
        run: docker run --rm -v $(pwd):/zap/wrk -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://host.docker.internal:8000 -r zap_report.html
